# Generated by Django 2.1.5 on 2019-02-11 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('public_id', models.CharField(max_length=225, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('통화명', models.CharField(max_length=80)),
                ('심볼', models.CharField(max_length=80)),
                ('현재가', models.DecimalField(decimal_places=5, max_digits=10)),
                ('전일대비', models.DecimalField(decimal_places=5, max_digits=10)),
                ('등락률', models.DecimalField(decimal_places=5, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mw_finance.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('public_id', models.CharField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
