# Generated by Django 2.1.5 on 2019-02-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mw_finance', '0002_menu_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklist',
            old_name='public_id',
            new_name='token',
        ),
    ]
