# Generated by Django 2.1.5 on 2019-02-19 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mw_finance', '0004_auto_20190214_0406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',)},
        ),
    ]
