# Generated by Django 2.1.5 on 2019-02-19 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mw_finance', '0005_auto_20190219_0154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
