# Generated by Django 2.1.5 on 2019-02-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mw_finance', '0006_auto_20190219_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
