# Generated by Django 2.1.5 on 2019-02-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mw_finance', '0007_auto_20190222_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
