# Generated by Django 2.1.5 on 2019-02-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mw_finance', '0008_auto_20190222_0157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
